### ISSUE TITLE
Accidentally attacks HAM guard

### ISSUE THREAD

**Issue by casual1** [Flamezzz/FClueHunterEasy#5]
Enters the ham camp with low hp, accidentally clicks the guard while wanting to click a tile, gets in fight, might die. Happens rarely.

**Comment by casual1** [comment]
Okay, I guess this is solved by enabling the right-click-everything setting. sorry.

**Comment by Flamezzz** [comment]
I didn't know this could still happen, I'll check if I can detect if that setting is enabled to show a message if it isn't.

It should never actually die since it will renew food if it needs food and there's no food left.

**Comment by Flamezzz** [comment]
Now shows a message if always right-click is not enabled.
